### ISSUE TITLE
URL manipulation

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/hippo#128]
https://localhost:44371/caesfarm/ shows no content 
https://localhost:44371/caesfarm2/pendingapproval shows text even though cluster doesn't exist

**Comment by srkirkland** [comment]
For first url, we should probably make that just resolve to the home component or a new cluster home one.

For the second one... that is an interesting question.  not sure what we should do there.  Perhaps the best is to add our list of clusters to the context?  That way it's easy to check for valid clusters.  And maybe then we update conditional route so that the route only shows if it's one of the valid ones?
